#!/bin/bash
set -e
cd "$(dirname "$0")"/..

TEST_FILES="test-data/*.cx $(find test-data -name main.cx)"

for fn in $TEST_FILES; do
    echo "building $fn:"
    dist/build/crux/crux "$fn"
    echo
done
