#!/bin/bash
set -e
cd "$(dirname "$0")"/..

TEST_FILES="test-data/*.sk $(find test-data -name main.sk)''"

for fn in $TEST_FILES; do
    echo "running $fn:"
    dist/build/sneak/sneak "$fn" | node
    echo
done
