#!/usr/bin/env bash

# TODO: detect non-system stack installs too
STACK=stack

BUILD_DIR=`"$STACK" path --local-install-root`/bin/web-playground-exe.jsexe
SRC="lib.js out.js rts.js runmain.js"

"$STACK" build

for s in $SRC; do
    cp $BUILD_DIR/$s stage
done
