#!/usr/bin/env bash

set -e
cd "$(dirname "$0")"/..

# TODO: detect non-system stack installs too
STACK=stack
BUILD_DIR=`"$STACK" path --local-install-root`/bin/crux-js-exe.jsexe
SRC="rts.js lib.js out.js" # we do our own runmain.js

"$STACK" build
mkdir -p dist
cat jsbits/wrap.intro.js > dist/crux.js
for src in $SRC; do
    cat "$BUILD_DIR/$src" >> dist/crux.js
done
cat jsbits/wrap.outro.js >> dist/crux.js

cp dist/crux.js stage/
mkdir -p npm/cruxlang/src/
cp dist/crux.js npm/cruxlang/src/
sass stage/style.scss > stage/style.css

(cd ../crux && "$STACK" build)
CRUX=$(cd ../crux && "$STACK" exec which crux)
echo "CRUX: $CRUX"
"$CRUX" build
